stages:
  data_collection:
    cmd: python src/data_collection.py
    deps:
    - src/data_collection.py
    outs:
    - data/raw
  pre_processing:
    cmd: python src/data_preprocessing.py
    deps:
    - data/raw
    - src/data_preprocessing.py
    outs:
    - data/processed
  model_build:
    cmd: python src/model_building.py
    deps:
    - data/processed/
    - src/model_building.py
    outs:
    - model.pkl
  model_evaluation:
    cmd: python src/model_evl.py
    deps:
    - model.pkl
    - src/model_evl.py
    metrics:
    - metrics.json
